name: Deploy to Azure Web App - gptserge2-api

on:
  push:
    branches:
      - main  # Déploie chaque fois qu'on pousse sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Déploiement vers Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: gptserge2-api                      # NOM EXACT dans Azure
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Ton secret GitHub
          package: .                                    # Déploie tout le dossier racine
